name: Go func tests

env:
  cc_id: "71ea1d39c818cae21ebab378ebac0d16f613325588766d03c3fa146876bc9e15"
  code_dir: "mainpkg"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        pkg: [anotherpkg, mainpkg]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...
        working-directory: ${{ matrix.pkg }}

      - name: Test
        run: |
          mkdir -p coverage
          go test -v ./... -coverprofile=coverage/${{ matrix.pkg }}_coverage.out
          
      - name: Save partial coverage as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/${{ matrix.pkg }}_coverage.out
      
  upload_coverage:
    runs-on: ubuntu-latest

    needs:
      - test

    steps:
      - uses: actions/checkout@v2

      - name: Download partial coverages
        uses: actions/download-artifact@v2
        with:
          name: coverage
          path: coverage

      - name: Format, sum & upload results to Code Climate
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ env.cc_id }}
        with:
          debug: true
          coverageLocations: coverage/*.out:gocov

